src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <label>Available Balance</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Limit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction Limit</label>
        <referenceTo>Transaction_Limit__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Transaction Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Transaction__c</fullName>
        <label>Maximum Debit Allowed per Transaction</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Day__c</fullName>
        <label>Maximum Transactions Allowed per Day</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Month__c</fullName>
        <label>Maximum Transactions Allowed per Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewDownloadStatementsControllerTest.cls
/*
  *  Purpose         :    Test class for SearchTransactionsController
  *  Created By      :    Vishal Tourani
  *  Created Date    :    2022/10/17
  *  Revision Logs   :    V_1.0 - Created - 2022/10/17
*/
@isTest
public class ViewDownloadStatementsControllerTest {
	
    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    Setup method to create records
      * Params        :    Void
      * Return        :    Void
    */
    @testSetup 
    public static void setup(){
        Transaction_Limit__c testLimit = new Transaction_Limit__c(Name = 'VIP', Maximum_Debit_Allowed_per_Transaction__c = 2000, 
                                                                  Maximum_Debit_Allowed_per_Day__c = 2000, Maximum_Debit_Allowed_per_Month__c = 10000, 
                                                                  Maximum_Transactions_Allowed_per_Day__c = 6, Maximum_Transactions_Allowed_per_Month__c = 10);  
        Insert testLimit;
        Contact testContact = new Contact(FirstName = 'Contact Record', LastName = 'for Test', Status__c = 'Active', Available_Balance__c = 500000, Transaction_Limit__c = testLimit.Id, Email = 'test@fexle.com');
    	Insert testContact;
        
        List<Transaction_Entry__c> listTransactionEntry = new List<Transaction_Entry__c>(); 
        for(Integer i=100; i<600; i+=100){
        	Transaction_Entry__c testEntry = new Transaction_Entry__c(Contact__c = testContact.Id, Type__c = 'Credit', Transaction_Date__c = Date.today(), Status__c = 'Completed', Amount__c = i);
            listTransactionEntry.add(testEntry);
        }
    	Insert listTransactionEntry;
    }
    
    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    To test queried records
      * Params        :    Void
      * Return        :    Void
    */
    @isTest
    public static void testGetTransactionRecords(){
        Test.startTest();
        Contact objContact = [Select Id, Account_Number__c from Contact LIMIT 1];
        List<Transaction_Entry__c> listEntry = ViewDownloadStatementsController.getTransaction(Date.Today()-1, Date.Today()+1, objContact.Id);
        Test.stopTest();
        System.assertEquals(5, listEntry.size());
    }
    
    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    To Csv file generation of Transaction records
      * Params        :    Void
      * Return        :    Void
    */
    @isTest
    public static void testGetTransactionCsv(){
        Test.startTest();
        Contact objContact = [Select Id, Account_Number__c from Contact LIMIT 1];
        List<Transaction_Entry__c> listEntry = ViewDownloadStatementsController.getTransaction(Date.Today()-1, Date.Today()+1, objContact.Id);
        ViewDownloadStatementsController.getTransactionCsv();
        Test.stopTest();
    }
    
    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    To Csv file generation of Transaction records
      * Params        :    Void
      * Return        :    Void
    */
    @isTest
    public static void testSendTransactionEmailAttachment(){
        Test.startTest();   
        Contact objContact = [Select Id, Account_Number__c from Contact LIMIT 1];
        ViewDownloadStatementsController.sendTransactionEmailAttachment((Date.Today()-1).format(), (Date.Today()+1).format(), objContact.Id);
        Test.stopTest();
    }
}