src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <displayFormat>{00000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Transaction Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SearchTransactionsController.cls
public class SearchTransactionsController{    
    public Decimal minAmount {set;get;}
    public Decimal maxAmount {set;get;}
    public Date startDate {set;get;}
    public Date endDate {set;get;}
    public String entryName {set;get;}
    public String status {set;get;}
    public String accNumber {set;get;}
    public List<Transaction_Entry__c> listTransactions {set;get;}

    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    Method to get Transaction Status options
      * Params        :    Void
      * Return        :    List<SelectOption>
    */
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Pending', 'Pending'));
        options.add(new SelectOption('Completed', 'Completed'));
        options.add(new SelectOption('Cancelled', 'Cancelled'));
        return options;
    }

    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    Method to query Transaction records
      * Params        :    Void
      * Return        :    Void
    */
    public void getTransactionRecords()
    {
        String stringQuery = 'SELECT Name, Amount__c, Type__c, Transaction_Date__c, Status__c, Contact__r.Account_Number__c FROM Transaction_Entry__c WHERE Contact__r.Account_Number__c = \'' + accNumber + '\'' ;

        if((minAmount != null) && (maxAmount != null)){   
            stringQuery = stringQuery +' AND Amount__c >= '+ minAmount + ' AND Amount__c <= '+ maxAmount +' ';
        }
        
        if((startDate != null) && (endDate != null)){
            //Converting date to string 
            Date sDate = date.newinstance(startDate.year(), startDate.month(), startDate.day());
			String startDateString = String.valueOf(sDate);
            
            Date eDate = date.newinstance(endDate.year(), endDate.month(), endDate.day());
			String endDateString = String.valueOf(endDate);
            
            
            stringQuery = stringQuery +' AND Transaction_Date__c >= '+ startDateString + ' AND Transaction_Date__c <= '+ endDateString +' ';
        }
        
        if(!String.isBlank(entryName)){
            stringQuery = stringQuery +' AND Name = \'' + entryName + '\''  ;
        }
        
        if(status != null){
            stringQuery = stringQuery +' AND Status__c = \'' + status + '\''  ;
        }
		
        //Assigning SOQL to list
        listTransactions = Database.query(stringQuery);
    } 

    
}