src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Limit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction Limit</label>
        <referenceTo>Transaction_Limit__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{0000}</displayFormat>
        <label>Transaction Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Day__c</fullName>
        <label>Maximum Transactions Allowed per Day</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Month__c</fullName>
        <label>Maximum Transactions Allowed per Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionEntryTriggerHelper.cls
/*
  *  Purpose         :    Helper class for Transaction Entry
  *  Created By      :    Vishal Tourani
  *  Created Date    :    2022/10/08
  *  Revision Logs   :    V_1.0 - Created - 2022/10/08
*/
public class TransactionEntryTriggerHelper{

    /*
      * Created By    :    Vishal Tourani
      * Purpose       :    Method to check Contact Limits
      * Params        :    List<Transaction_Entry__c> newList
      * Return        :    Void
    */
    public static void checkContactLimits(List<Transaction_Entry__c> newList){
        Set<Id> setContactId = new Set<Id>();     
        
        for(Transaction_Entry__c newEntry : newList){
            if(newEntry.Type__c == 'Debit'){
                setContactId.add(newEntry.Contact__c);
            }
        }

        if(!setContactId.isEmpty()){
        Map<Id, Contact> mapContact = new Map<Id, Contact>([Select Id, Transaction_Limit__r.Maximum_Debit_Allowed_per_Day__c, 
                                                            Transaction_Limit__r.Maximum_Debit_Allowed_per_Month__c,Transaction_Limit__r.Maximum_Transactions_Allowed_per_Day__c,
                                                            Transaction_Limit__r.Maximum_Transactions_Allowed_per_Month__c from Contact 
                                                            where Id IN :setContactId AND Transaction_Limit__r.Id != null]);

        //Getting Records to check per day debit and transaction limit
        List<AggregateResult> listPerDay = [Select SUM(Amount__c) Amount_Total, COUNT(ID) Count_Entry, Contact__r.Id idContact from Transaction_Entry__c 
                                            where Transaction_Date__c = TODAY AND Status__c != 'Cancelled' AND Type__c = 'Debit' Group By Contact__r.Id];
        Map<Id, Decimal> mapContactIdWithPerDayDebit = new Map<Id, Decimal>();
        Map<Id, Decimal> mapContactIdWithPerDayTransaction = new Map<Id, Decimal>();
        for(AggregateResult perDay : listPerDay){
            mapContactIdWithPerDayDebit.put((Id)perDay.get('idContact'), (Decimal)perDay.get('Amount_Total'));
            mapContactIdWithPerDayTransaction.put((Id)perDay.get('idContact'), (Decimal)perDay.get('Count_Entry'));
        }

        //Getting Records to check per month debit and transaction limit
        List<AggregateResult> listPerMonth = [Select SUM(Amount__c) Amount_Total, COUNT(ID) Count_Entry, Contact__r.Id idContact from Transaction_Entry__c 
                                              where Transaction_Date__c = THIS_MONTH AND Status__c != 'Cancelled' AND Type__c = 'Debit' Group By Contact__r.Id];
        Map<Id, Decimal> mapContactIdWithPerMonthDebit = new Map<Id, Decimal>();
        Map<Id, Decimal> mapContactIdWithPerMonthTransaction = new Map<Id, Decimal>();
        for(AggregateResult perMonth : listPerMonth){
            mapContactIdWithPerMonthDebit.put((Id)perMonth.get('idContact'), (Decimal)perMonth.get('Amount_Total'));
            mapContactIdWithPerMonthTransaction.put((Id)perMonth.get('idContact'), (Decimal)perMonth.get('Count_Entry'));
        }

        for(Transaction_Entry__c newEntry : newList){
            Decimal perDayDebitLimit = mapContact.get(newEntry.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_per_Day__c;
            Decimal perDayTransactionLimit = mapContact.get(newEntry.Contact__c).Transaction_Limit__r.Maximum_Transactions_Allowed_per_Day__c;
            Decimal perMonthDebitLimit = mapContact.get(newEntry.Contact__c).Transaction_Limit__r.Maximum_Debit_Allowed_per_Month__c;
            Decimal perMonthTransactionLimit = mapContact.get(newEntry.Contact__c).Transaction_Limit__r.Maximum_Transactions_Allowed_per_Month__c;

            Decimal perDayDebitDone = mapContactIdWithPerDayDebit.get(newEntry.Contact__c);
            Decimal perDayTransactionDone = mapContactIdWithPerDayTransaction.get(newEntry.Contact__c);
            Decimal perMonthDebitDone = mapContactIdWithPerMonthDebit.get(newEntry.Contact__c);
            Decimal perMonthTransactionDone = mapContactIdWithPerMonthTransaction.get(newEntry.Contact__c);

            //Checking per day debit limit
            if(perDayDebitDone != null){
                if(perDayDebitLimit < (perDayDebitDone + newEntry.Amount__c)){
                    newEntry.addError('You have exceeded per day Debit limit');        
                }
                else{
                    mapContactIdWithPerDayDebit.put(newEntry.Contact__c, perDayDebitDone + newEntry.Amount__c);
                }
            }
            else{
                mapContactIdWithPerDayDebit.put(newEntry.Contact__c, newEntry.Amount__c);
            }

            //Checking per day transaction limit
            if(perDayTransactionDone != null){
                if(perDayTransactionLimit == perDayTransactionDone){
                    newEntry.addError('You have exceeded per day Transaction limit');        
                }
                else{
                    mapContactIdWithPerDayTransaction.put(newEntry.Contact__c, perDayTransactionDone+1);
                }
            }
            else{
                mapContactIdWithPerDayTransaction.put(newEntry.Contact__c, 1);
            }

            //Checking per month debit limit
            if(perMonthDebitDone != null){
                if(perMonthDebitLimit < (perMonthDebitDone + newEntry.Amount__c)){
                    newEntry.addError('You have exceeded per month Debit limit');        
                }
                else{
                    mapContactIdWithPerMonthDebit.put(newEntry.Contact__c, perMonthDebitDone+newEntry.Amount__c);
                }
            }
            else{
                mapContactIdWithPerMonthDebit.put(newEntry.Contact__c, newEntry.Amount__c);
            }

            //Checking per month transaction limit
            if(perMonthTransactionDone != null){
                if(perMonthTransactionLimit == perMonthTransactionDone){
                    newEntry.addError('You have exceeded per month Transaction limit');        
                }
                else{
                    mapContactIdWithPerMonthTransaction.put(newEntry.Contact__c, perMonthTransactionDone+1);
                }
            }
            else{
                mapContactIdWithPerMonthTransaction.put(newEntry.Contact__c, 1);    
            }     
        }
        }
    }
}